
import re
import requests
from bs4 import BeautifulSoup

#creating a list of links, where each item of the list represents a new page of the search results
linklist = ["https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_search_result_summary_SearchResultSummaryPortlet_INSTANCE_J3bVc3AR9wJT&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275339248&&facet.language=ENG&resultsPerPage=50",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275340136&&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=51&QUERY_ID=275340136",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275340362&&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=101&QUERY_ID=275340362",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275340683&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=151&QUERY_ID=275340683",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275340880&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=201&QUERY_ID=275340880",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275341023&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=251&QUERY_ID=275341023",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275341068&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=301&QUERY_ID=275341068",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342152&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=351&QUERY_ID=275342152",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342189&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=401&QUERY_ID=275342189",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342207&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=451&QUERY_ID=275342207",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342233&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=501&QUERY_ID=275342233",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342251&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=551&QUERY_ID=275342251",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342262&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=601&QUERY_ID=275342262",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342282&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=651&QUERY_ID=275342282",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342296&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=701&QUERY_ID=275342296",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342421&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=751&QUERY_ID=275342421",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342430&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=801&QUERY_ID=275342430",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342444&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=851&QUERY_ID=275342444",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342458&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=901&QUERY_ID=275342458",
            "https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_pagination_PaginationPortlet_INSTANCE_eYu9jIuZAUpO&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUSummariesOfLegislation&facet.documentFormat=PDF&facet.language=ENG&facet.documentYear=2021,2020,2019,2022&facet.eurovoc.domain=52&selectedSubjectId=52&elementType=0&sortBy=PUBLICATION_DATE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=275342615&&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&facet.language=ENG&resultsPerPage=50&startRow=951&QUERY_ID=275342615"]

#scraping the PDF-download links from the search pages by looping over the list of links
ugly_links = []
for link in linklist:
    url = link
    html_text = requests.get(url)
    soup = BeautifulSoup(html_text.text, features = "html.parser")
    get_pdf_links = soup.findAll("a", {"data-format": "PDF"}) #making sure it only downloads .pdf files and not .doc files
    ugly_links = ugly_links + get_pdf_links

print(ugly_links)

#looping over the ugly_links list to extract the url that is hidden as an uri
document_links = []
proxy = {"https": "http://51.159.163.198:88", "https": "http://46.227.37.145:1088", "https": "http://95.85.254.138:5678"}
for item in ugly_links:
    uri = item.get("data-uri")
    amp_url = "https://op.europa.eu" + uri
    url = re.sub('amp;','',amp_url) #removing 'amp;' from the link that is added in scraping
    document_links.append(url)


#downloading PDF files to data folder
#def download_file(link, folder):

